# === BASH ALIASES === #

# A
# B
# C
# D
# E
# F
# G
alias grep='grep --color=always'
# H
# I
# J
# K
# L
alias ll='ls -ahlOp'
# M
# N
alias neofetch='neofetch --config "$HOME/.neofetch"'
# O
# P
# Q
# R
# S
# T
# U
# V
# W
# X
# Y
# Z
